/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AutoDownloadBot': RouteRecordInfo<'/AutoDownloadBot', '/AutoDownloadBot', Record<never, never>, Record<never, never>>,
    '/Destination': RouteRecordInfo<'/Destination', '/Destination', Record<never, never>, Record<never, never>>,
    '/Forwarder': RouteRecordInfo<'/Forwarder', '/Forwarder', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/ImportList': RouteRecordInfo<'/ImportList', '/ImportList', Record<never, never>, Record<never, never>>,
    '/InvoiceReport': RouteRecordInfo<'/InvoiceReport', '/InvoiceReport', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/SecretAdmin': RouteRecordInfo<'/SecretAdmin', '/SecretAdmin', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/TotalDownloadReport': RouteRecordInfo<'/TotalDownloadReport', '/TotalDownloadReport', Record<never, never>, Record<never, never>>,
    '/UploadFile': RouteRecordInfo<'/UploadFile', '/UploadFile', Record<never, never>, Record<never, never>>,
    '/User': RouteRecordInfo<'/User', '/User', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/AutoDownloadBot.vue': {
      routes: '/AutoDownloadBot'
      views: never
    }
    'src/pages/Destination.vue': {
      routes: '/Destination'
      views: never
    }
    'src/pages/Forwarder.vue': {
      routes: '/Forwarder'
      views: never
    }
    'src/pages/HomeView.vue': {
      routes: '/HomeView'
      views: never
    }
    'src/pages/ImportList.vue': {
      routes: '/ImportList'
      views: never
    }
    'src/pages/InvoiceReport.vue': {
      routes: '/InvoiceReport'
      views: never
    }
    'src/pages/Login.vue': {
      routes: '/Login'
      views: never
    }
    'src/pages/NotFound.vue': {
      routes: '/NotFound'
      views: never
    }
    'src/pages/Profile.vue': {
      routes: '/Profile'
      views: never
    }
    'src/pages/Register.vue': {
      routes: '/Register'
      views: never
    }
    'src/pages/SecretAdmin.vue': {
      routes: '/SecretAdmin'
      views: never
    }
    'src/pages/Settings.vue': {
      routes: '/Settings'
      views: never
    }
    'src/pages/TotalDownloadReport.vue': {
      routes: '/TotalDownloadReport'
      views: never
    }
    'src/pages/UploadFile.vue': {
      routes: '/UploadFile'
      views: never
    }
    'src/pages/User.vue': {
      routes: '/User'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
