# Generated by Django 6.0 on 2025-12-09 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
