# Generated by Django 6.0 on 2025-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimport',
            name='bot_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderimport',
            name='bot_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='orderimport',
            name='generated_zip',
            field=models.FileField(blank=True, null=True, upload_to='downloads/zips/'),
        ),
    ]
