# Generated by Django 6.0 on 2025-12-26 03:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderimport_bot_message_orderimport_bot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimport',
            name='folder_name',
            field=models.CharField(blank=True, default='uploads', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderimport',
            name='file',
            field=models.FileField(upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='orderimport',
            name='generated_zip',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_zip_path),
        ),
    ]
